################ Latvian language ##################
[lv]
languageName = "LV"
languageCode = "lv-lv"
contentDir = "content/latvian"
weight = 1

################ English language ##################
[en]
languageName = "EN"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
